//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garbage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Garbage.GStrings", typeof(GStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want clear target history?.
        /// </summary>
        internal static string ClearPathHistoryMessage {
            get {
                return ResourceManager.GetString("ClearPathHistoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\GARBAGE.
        /// </summary>
        internal static string DefaultPath {
            get {
                return ResourceManager.GetString("DefaultPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %Y.%M.%D\%N [%h-%m-%s]%X.
        /// </summary>
        internal static string DefaultTemplate {
            get {
                return ResourceManager.GetString("DefaultTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN: Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example.txt.
        /// </summary>
        internal static string ExampleFileName {
            get {
                return ResourceManager.GetString("ExampleFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete history files from all folders?.
        /// </summary>
        internal static string HistoryAskDeleteMessage {
            get {
                return ResourceManager.GetString("HistoryAskDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  history file(s) was deleted!.
        /// </summary>
        internal static string HistoryDeletedMessage {
            get {
                return ResourceManager.GetString("HistoryDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # GARBAGE HISTORY #.TXT.
        /// </summary>
        internal static string HistotyFileName {
            get {
                return ResourceManager.GetString("HistotyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN: Information.
        /// </summary>
        internal static string InfoCaption {
            get {
                return ResourceManager.GetString("InfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        internal static string LastUseNever {
            get {
                return ResourceManager.GetString("LastUseNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving successfully done!.
        /// </summary>
        internal static string MovingSuccessMessage {
            get {
                return ResourceManager.GetString("MovingSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No space in destination path!.
        /// </summary>
        internal static string NoSpaceMessage {
            get {
                return ResourceManager.GetString("NoSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found!.
        /// </summary>
        internal static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in target path field!.
        /// </summary>
        internal static string PathErrorMessage {
            get {
                return ResourceManager.GetString("PathErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN: Question.
        /// </summary>
        internal static string QuestionCaption {
            get {
                return ResourceManager.GetString("QuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &quot;Send to&quot; in context menu to find &quot;Garbage&quot;.
        /// </summary>
        internal static string SendToInfoMessage {
            get {
                return ResourceManager.GetString("SendToInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in template field!.
        /// </summary>
        internal static string TemplateErrorMessage {
            get {
                return ResourceManager.GetString("TemplateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN: Warning.
        /// </summary>
        internal static string WarningCaption {
            get {
                return ResourceManager.GetString("WarningCaption", resourceCulture);
            }
        }
    }
}
